[package]
org = "thisaru"
name = "movie_rating_system"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerina"
name="graphql"
version="1.13.2"
repository="local"

